platform :ios, '7.0'

pod "AFNetworking", "~> 2.5.4"
pod "Cloudinary", "~> 1.0.13"
pod "HexColors", "~> 2.2"
pod "LBBlurredImage", :git => "git@github.com:lukabernardi/LBBlurredImage.git"
pod "CHTCollectionViewWaterfallLayout", "~> 0.9.1"
pod "ALAlertBanner", "~> 0.3.1"
pod "Mixpanel", "~> 2.8.1"
pod "GSIndeterminateProgressBar", :git => "git@github.com:hectorups/GSIndeterminateProgressBar.git"
pod "SCLAlertView-Objective-C", "~> 0.7.3"
pod "OvershareKit", "~>1.3.1"
pod "JTSImageViewController", "~> 1.4"
pod "TWRDownloadManager", "~> 1.1.1"
pod "MRProgress", "~> 0.8.2"
pod "SwipeView", "~> 1.3.2"
pod "COSTouchVisualizer", "~> 1.0.6"