platform :ios, '7.0'

pod "AFNetworking"
pod "Cloudinary"
pod "HexColors", "~> 2.2"
pod "LBBlurredImage", :git => "git@github.com:lukabernardi/LBBlurredImage.git"
pod "CHTCollectionViewWaterfallLayout"
pod "ALAlertBanner", "~> 0.3.1"
pod "Mixpanel", "~> 2.6.0"
pod "GSIndeterminateProgressBar", :git => "git@github.com:hectorups/GSIndeterminateProgressBar.git"
pod "SCLAlertView-Objective-C"
pod "OvershareKit", "~>1.3.1"
pod "JTSImageViewController", "~> 1.4"
pod "TWRDownloadManager", "~> 1.1.1"
pod "MRProgress"
pod "SwipeView", "~> 1.3.2"
pod "COSTouchVisualizer"
